# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' 'compUpdate' update orientation with 3-axis acc and gyr data
#'
#' @param acc A numeric 3-vector of 3-axis accelerometer readings in g
#' @param gyr A numeric 3-vector of 3-axis gyroscope readings in rad/sec
#' @param dt A numeric of time duration in sec
#' @param initQuat A numeric 4-vector of the starting orientation in quaternion
#' @param gain A numeric gain factor between 0 and 1
#' @returns A numeric 4-vector of the ending orientation in quaternion
#' @export
#'
#' @examples
#' compUpdate(c(0, 0, -1), c(1, 0, 0), 0.1, c(1, 0, 0, 0), 0.1)
#'
compUpdate <- function(acc, gyr, dt, initQuat, gain) {
    .Call(`_imuf_compUpdate`, acc, gyr, dt, initQuat, gain)
}

